[package]
name = "rust_calculate"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_decimal = { version = "1.37.1", features = ["macros", "maths"] }
thiserror = "2.0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
